#
###################################
# Site wide configuration
####################################
#
title: Zhihang Dong
email: zdong@uw.edu
description: Ph.D. Student at the University of Washington
url: https://zdong1.github.io# the base hostname & protocol for your site
keywords: ["data science", "natural language processing"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Zhihang Dong
  avatar: leonids-logo.png
  job: "A jekyll theme"
  bio: "Ph.D. Student specialized in Data Science"
  email:
  disqus-shortname:
  twitter: zdong6#username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: zdong1#username
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: zhihangdong #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
